/* Gentle Fuel virtual-pet engine: one reusable Three.js prototype for every starter. */
let THREE=null;

const STORE='gentle-fuel-pet-v1';
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));
const PETS={
  bunny:{label:'Bunbun',kind:'Moon Rabbit',body:0xffe8dc,accent:0xf3a3b5,ear:'long'},
  kitty:{label:'Mimi',kind:'Cloud Kitty',body:0xded9f3,accent:0xa49add,ear:'point'},
  mochi:{label:'Mochi',kind:'River Otter',body:0xb98663,accent:0xf4d6ac,ear:'round'}
};

function record(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function companionFrom(pet,name){return {id:pet,name:name||PETS[pet].label,createdAt:Date.now(),stats:{hunger:72,energy:78,happiness:74,affection:48,curiosity:66},action:'idle',lastSeen:Date.now(),version:2}}
function persist(companion){const data=record()||{days:{},pet:companion.id,month:new Date().toISOString().slice(0,7),achievements:[]};data.pet=companion.id;data.companion=companion;localStorage.setItem(STORE,JSON.stringify(data));window.gentleFuelCompanion=companion}
function stageFor(stats){if(stats.energy<22)return 'sleep';if(stats.hunger<25)return 'hungry';if(stats.happiness<30)return 'quiet';return 'curious'}
function xpFor(data){if(typeof data?.xp==='number')return data.xp;return Object.values(data?.days||{}).reduce((sum,d)=>sum+(d.meals||[]).filter(m=>(d.activity==='Rest'?['breakfast','lunch','dinner']:['workout','breakfast','lunch','dinner']).includes(m)).length*.1,0)}
function levelFor(data){return Math.min(4,Math.floor(xpFor(data)/4)+1)}
function spriteStage(level){return Math.min(3,Math.max(0,level-1))}
function spriteSource(id){return id==='bunny'?'pets/bunny-stages-v2.png':`pets/${id}-stages.png`}
const guideImages={};

class SpritePetView{
  constructor(host,config,companion){this.host=host;this.companion=companion;this.id=companion.id;host.innerHTML='';this.canvas=document.createElement('canvas');this.canvas.className='fallback-pet-canvas';this.canvas.width=640;this.canvas.height=460;host.append(this.canvas);this.ctx=this.canvas.getContext('2d');this.image=new Image();this.image.src=spriteSource(this.id);this.image.onload=()=>this.draw();this.action='idle';this.until=0;this.tick();}
  react(action){this.action=action;this.until=Date.now()+2500;this.draw()}
  tick(){this.draw();requestAnimationFrame(()=>this.tick())}
  draw(){const ctx=this.ctx,w=this.canvas.width,h=this.canvas.height,now=Date.now(),level=levelFor(record()),stage=spriteStage(level),lively=now<this.until;ctx.clearRect(0,0,w,h);ctx.fillStyle='#cfe3d1';ctx.fillRect(0,0,w,h);ctx.fillStyle='#b4d1b7';ctx.beginPath();ctx.ellipse(w/2,h*.86,w*.31,h*.07,0,0,Math.PI*2);ctx.fill();if(!this.image.complete||!this.image.naturalWidth){ctx.fillStyle='#fff';ctx.font='72px system-ui';ctx.textAlign='center';ctx.fillText(PETS[this.id].label,w/2,h/2);return}const panels=this.id==='bunny'?4:5,sw=this.image.naturalWidth/panels,sh=this.image.naturalHeight,tmp=document.createElement('canvas');tmp.width=sw;tmp.height=sh;const t=tmp.getContext('2d');t.drawImage(this.image,stage*sw,0,sw,sh,0,0,sw,sh);const pix=t.getImageData(0,0,sw,sh);for(let i=0;i<pix.data.length;i+=4){const r=pix.data[i],g=pix.data[i+1],b=pix.data[i+2];if(r>180&&b>130&&g<110)pix.data[i+3]=0}t.putImageData(pix,0,0);let x=w/2,y=h*.96,bob=Math.sin(now/260)*(lively?.045:.014)*h,turn=0,scale=1.24+stage*.05;if(lively&&this.action==='call')x+=Math.sin(now/120)*w*.12;if(lively&&this.action==='play'){bob+=Math.abs(Math.sin(now/105))*h*.16;turn=Math.sin(now/125)*.13;scale*=1.04}if(lively&&this.action==='pet'){bob-=Math.abs(Math.sin(now/145))*h*.045;scale*=1.06}if(lively&&this.action==='sleep'){bob=Math.sin(now/600)*h*.012;turn=-.08}const dh=h*scale,dw=sw/sh*dh;ctx.save();ctx.translate(x,y+bob);ctx.rotate(turn);ctx.drawImage(tmp,-dw/2,-dh,dw,dh);ctx.restore();if(lively&&this.action==='feed'){ctx.font='42px system-ui';ctx.textAlign='center';ctx.fillText('🥕',x+dw*.3,y-dh*.12)}if(lively&&this.action==='pet'){ctx.font='30px system-ui';ctx.textAlign='center';ctx.fillText('♥  ♥',x,y-dh*.88)}if(lively&&this.action==='call'){ctx.font='25px system-ui';ctx.textAlign='center';ctx.fillText('Bunbun!  ♫',w/2,78)}if(lively&&this.action==='sleep'){ctx.font='31px system-ui';ctx.textAlign='center';ctx.fillText('Z z z',x+dw*.25,y-dh*.65)}}
}

class PetView{
  constructor(host,config,companion,mini=false){
    this.host=host;this.config=config;this.companion=companion;this.mini=mini;this.clock=new THREE.Clock();this.mood='idle';this.moodUntil=0;this.blinkUntil=0;this.nextBlink=2+Math.random()*3;this.nextIdle=3+Math.random()*5;
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color(mini?0xcfe3d1:0xeaf4ed);this.camera=new THREE.PerspectiveCamera(35,1,.1,50);this.camera.position.set(0,1.9,5.2);
    this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(this.renderer.domElement);
    this.scene.add(new THREE.HemisphereLight(0xffffff,0x4a6a58,2.2));const key=new THREE.DirectionalLight(0xfff3df,3);key.position.set(3,5,4);key.castShadow=true;key.shadow.mapSize.set(512,512);this.scene.add(key);const rim=new THREE.PointLight(0xc0b4ff,12,12);rim.position.set(-3,2,2);this.scene.add(rim);
    const floor=new THREE.Mesh(new THREE.CircleGeometry(3.7,48),new THREE.MeshStandardMaterial({color:mini?0xb9d8bc:0xd7ead9,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;this.scene.add(floor);
    this.root=new THREE.Group();this.scene.add(this.root);this.build();new ResizeObserver(()=>this.resize()).observe(host);this.resize();this.animate();
  }
  mat(color,rough=.72){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.02})}
  mesh(geo,mat,pos,scale){const m=new THREE.Mesh(geo,mat);m.position.set(...pos);if(scale)m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;this.root.add(m);return m}
  build(){const c=this.config,body=this.mat(c.body),accent=this.mat(c.accent),dark=this.mat(0x382d36),cream=this.mat(0xfff4e8);this.parts={};
    this.parts.body=this.mesh(new THREE.SphereGeometry(.83,32,24),body,[0,.96,0],[1,1.05,.92]);this.parts.head=this.mesh(new THREE.SphereGeometry(.67,32,24),body,[0,1.75,.05],[1.05,1,.96]);
    this.parts.belly=this.mesh(new THREE.SphereGeometry(.45,24,16),cream,[0,.86,.66],[.85,1,.18]);
    this.parts.leftEye=this.mesh(new THREE.SphereGeometry(.105,20,16),dark,[-.24,1.83,.62],[1,1,.45]);this.parts.rightEye=this.mesh(new THREE.SphereGeometry(.105,20,16),dark,[.24,1.83,.62],[1,1,.45]);
    this.parts.nose=this.mesh(new THREE.SphereGeometry(.07,16,12),accent,[0,1.65,.7],[1,.65,.45]);
    this.parts.leftFoot=this.mesh(new THREE.SphereGeometry(.25,20,16),body,[-.38,.32,.35],[1.2,.7,1]);this.parts.rightFoot=this.mesh(new THREE.SphereGeometry(.25,20,16),body,[.38,.32,.35],[1.2,.7,1]);
    if(c.ear==='long'){this.parts.ears=[this.mesh(new THREE.SphereGeometry(.2,20,16),accent,[-.34,2.48,0],[.7,2.4,.62]),this.mesh(new THREE.SphereGeometry(.2,20,16),accent,[.34,2.48,0],[.7,2.4,.62])];}
    if(c.ear==='point'){this.parts.ears=[this.mesh(new THREE.ConeGeometry(.31,.76,4),accent,[-.37,2.38,.02],[1,1,1]),this.mesh(new THREE.ConeGeometry(.31,.76,4),accent,[.37,2.38,.02],[1,1,1])];}
    if(c.ear==='round'){this.parts.ears=[this.mesh(new THREE.SphereGeometry(.28,18,14),body,[-.62,1.86,-.02],[1,1,.65]),this.mesh(new THREE.SphereGeometry(.28,18,14),body,[.62,1.86,-.02],[1,1,.65])];this.parts.tail=this.mesh(new THREE.SphereGeometry(.28,18,14),body,[.74,.86,-.15],[1.7,.55,.7]);}
    this.parts.armL=this.mesh(new THREE.SphereGeometry(.2,18,14),body,[-.78,1.05,.16],[.68,1.5,.68]);this.parts.armR=this.mesh(new THREE.SphereGeometry(.2,18,14),body,[.78,1.05,.16],[.68,1.5,.68]);
  }
  setAction(action,duration=2.4){this.mood=action;this.moodUntil=this.clock.getElapsedTime()+duration;this.companion.action=action;}
  randomIdle(){const s=this.companion.stats;const options=s.energy<28?['sleep','sit']:s.hunger<30?['hungry','call']:s.curiosity>70?['walk','look']:['idle','sit','look','walk'];this.setAction(options[Math.floor(Math.random()*options.length)],2+Math.random()*3)}
  react(kind){const s=this.companion.stats;if(kind==='feed'){s.hunger=clamp(s.hunger+26);s.energy=clamp(s.energy+5);s.happiness=clamp(s.happiness+9);this.setAction('eat',2.8)}if(kind==='pet'){s.affection=clamp(s.affection+12);s.happiness=clamp(s.happiness+5);this.setAction('happy',2)}if(kind==='call'){s.curiosity=clamp(s.curiosity+9);s.affection=clamp(s.affection+4);this.setAction('run',2.2)}if(kind==='play'){s.happiness=clamp(s.happiness+17);s.energy=clamp(s.energy-9);s.curiosity=clamp(s.curiosity+10);this.setAction('play',3.2)}if(kind==='sleep'){s.energy=clamp(s.energy+22);this.setAction('sleep',4.2)}persist(this.companion)}
  update(dt,t){const p=this.parts,act=this.mood;this.root.position.y=.08+Math.sin(t*2.1)*.035;this.root.rotation.y=Math.sin(t*.35)*.12;let bob=0,walk=0;
    if(t>this.nextBlink){this.blinkUntil=t+.14;this.nextBlink=t+2.1+Math.random()*4}const blink=t<this.blinkUntil ? .16 : 1;p.leftEye.scale.y=blink;p.rightEye.scale.y=blink;
    if(t>this.nextIdle&&t>this.moodUntil){this.randomIdle();this.nextIdle=t+3+Math.random()*5}if(t>this.moodUntil)this.mood='idle';
    if(act==='walk'||act==='run'||act==='play'){walk=Math.sin(t*(act==='run'?12:7));this.root.position.x=Math.sin(t*(act==='run'?1.9:1.1))*.35;bob=Math.abs(walk)*.1;p.leftFoot.rotation.x=walk*.7;p.rightFoot.rotation.x=-walk*.7;p.armL.rotation.x=-walk*.8;p.armR.rotation.x=walk*.8}
    else {this.root.position.x=0;p.leftFoot.rotation.x=0;p.rightFoot.rotation.x=0;p.armL.rotation.x=Math.sin(t*2)*.08;p.armR.rotation.x=-Math.sin(t*2)*.08}
    if(act==='sleep'){this.root.rotation.z=Math.sin(t*.8)*.09;p.head.rotation.z=.18;p.leftEye.scale.y=.06;p.rightEye.scale.y=.06;this.root.position.y=.02+Math.sin(t*1.3)*.025}else{p.head.rotation.z=0;this.root.rotation.z=0}
    if(act==='eat'){p.armL.rotation.z=Math.sin(t*9)*.7;p.armR.rotation.z=-Math.sin(t*9)*.7;p.head.rotation.x=Math.abs(Math.sin(t*5))*.2}else{p.head.rotation.x=0}
    if(act==='happy'){p.armL.rotation.z=Math.sin(t*8)*.9;p.armR.rotation.z=-Math.sin(t*8)*.9;bob=Math.abs(Math.sin(t*8))*.14}
    if(act==='sit'){p.body.scale.y=.9;p.head.position.y=1.62}else{p.body.scale.y=1.05;p.head.position.y=1.75}
    if(act==='look'||act==='call'){p.head.rotation.y=Math.sin(t*3)*.35}else p.head.rotation.y=0;
    this.root.position.y+=bob;this.camera.position.x=Math.sin(t*.22)*.22;this.camera.lookAt(0,1.25,0);
  }
  resize(){const w=this.host.clientWidth,h=this.host.clientHeight||260;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
  animate(){const tick=()=>{const dt=Math.min(this.clock.getDelta(),.05),t=this.clock.getElapsedTime();this.update(dt,t);this.renderer.render(this.scene,this.camera);requestAnimationFrame(tick)};tick()}
}

class CompanionController{
  constructor(){this.companion=null;this.views=[];this.hosts=[];this.init();setInterval(()=>this.companion&&this.render(),900)}
  init(){const stored=record();if(stored?.companion)this.companion=stored.companion;else if(stored?.pet){this.companion=companionFrom(stored.pet,PETS[stored.pet]?.label);persist(this.companion)}
    if(this.companion)this.mount();else this.showEncounter();
  }
  mount(){this.companion.stats??={hunger:72,energy:78,happiness:74,affection:48,curiosity:66};this.companion.lastSeen??=Date.now();this.drain();window.gentleFuelCompanion=this.companion;this.mountViews();this.bind();this.render();}
  mountViews(){const config=PETS[this.companion.id],View=this.companion.id==='bunny'?SpritePetView:(THREE?PetView:SpritePetView);this.views=[...document.querySelectorAll('[data-pet3d]')].map((host,i)=>new View(host,config,this.companion,i===0));}
  upgrade3D(){if(!THREE||!this.companion)return;document.querySelectorAll('[data-pet3d]').forEach(host=>host.innerHTML='');this.mountViews();this.render()}
  drain(){const elapsed=Math.min((Date.now()-this.companion.lastSeen)/3600000,12),s=this.companion.stats;s.hunger=clamp(s.hunger-elapsed*4);s.energy=clamp(s.energy-elapsed*2.5);s.happiness=clamp(s.happiness-elapsed*1.8);s.curiosity=clamp(s.curiosity+elapsed*1.2);this.companion.lastSeen=Date.now();persist(this.companion)}
  bind(){document.querySelectorAll('[data-pet-action]').forEach(b=>b.onclick=()=>this.interact(b.dataset.petAction));document.querySelectorAll('[data-pet3d]').forEach(host=>host.onclick=()=>this.interact('pet'));document.querySelectorAll('[data-change-pet]').forEach(b=>b.onclick=()=>this.changeCompanion(b.dataset.changePet));}
  interact(action){this.views.forEach(v=>v.react(action));this.companion.action=action;this.companion.lastSeen=Date.now();persist(this.companion);this.render();const messages={pet:`${this.companion.name} leans into your pats.`,feed:`${this.companion.name} happily munches the carrot!`,call:`${this.companion.name} hops over when called!`,play:`${this.companion.name} is bouncing with joy!`,sleep:`${this.companion.name} curls up for a little rest.`};document.querySelectorAll('[data-pet-status]').forEach(e=>e.textContent=messages[action]||'')}
  unlockIfGrown(data,level){if(level!==4)return false;data.achievements??=[];if(data.achievements.some(a=>a.pet===this.companion.id))return false;data.achievements.push({pet:this.companion.id,name:this.companion.name,xp:xpFor(data),date:new Date().toISOString().slice(0,10)});data.companion=this.companion;localStorage.setItem(STORE,JSON.stringify(data));return true}
  drawGuideSprite(canvas,id,stage){let image=guideImages[id];if(!image){image=guideImages[id]=new Image();image.src=spriteSource(id);image.onload=()=>this.collection(record()||{})}if(!image.complete||!image.naturalWidth)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,panels=id==='bunny'?4:5,sw=image.naturalWidth/panels,sh=image.naturalHeight,tmp=document.createElement('canvas');tmp.width=sw;tmp.height=sh;const t=tmp.getContext('2d');t.drawImage(image,stage*sw,0,sw,sh,0,0,sw,sh);const pix=t.getImageData(0,0,sw,sh);for(let i=0;i<pix.data.length;i+=4){const r=pix.data[i],g=pix.data[i+1],b=pix.data[i+2];if(r>180&&b>130&&g<110)pix.data[i+3]=0}t.putImageData(pix,0,0);ctx.clearRect(0,0,w,h);const scale=.84,dh=h*scale,dw=sw/sh*dh;ctx.drawImage(tmp,(w-dw)/2,h-dh,dw,dh)}
  collection(data,level=levelFor(data)){const host=document.querySelector('[data-pet-collection]');if(!host)return;const found=data.achievements||[],ids=['bunny','kitty','mochi'],stageNames=['Egg','Baby','Young','Fluffy'];let number=1;host.innerHTML=ids.map(id=>{const pet=PETS[id],item=found.find(a=>a.pet===id),active=id===this.companion.id;return Array.from({length:4},(_,stage)=>{const unlocked=Boolean(item)||(active&&stage<level),startable=!active&&!item&&stage===0,classes=`guide-card ${unlocked?'is-unlocked':'is-locked'} ${active&&stage===level-1?'is-growing':''}`;const body=`<span class="guide-number">${String(number++).padStart(4,'0')}</span><canvas class="guide-sprite" data-guide-sprite="${id}" data-guide-stage="${stage}" width="160" height="120"></canvas><b>${pet.label} · L${stage+1}</b><small>${item?'Collected':unlocked?'Unlocked':stageNames[stage]+' · locked'}</small>`;return startable?`<button class="${classes}" data-change-pet="${id}">${body}</button>`:`<article class="${classes}">${body}</article>`}).join('')}).join('')+Array.from({length:4},()=>`<article class="guide-card is-coming"><span class="guide-number">${String(number++).padStart(4,'0')}</span><span class="guide-silhouette">?</span><b>Coming soon</b><small>New friend</small></article>`).join('');host.querySelectorAll('[data-guide-sprite]').forEach(canvas=>this.drawGuideSprite(canvas,canvas.dataset.guideSprite,+canvas.dataset.guideStage));document.querySelectorAll('[data-collection-count]').forEach(e=>e.textContent=`${found.length} / 3 companions complete`)}
  changeCompanion(id){if(id===this.companion.id)return;if(!confirm(`Choose ${PETS[id].label}? Your current unfinished companion and its XP journey will be retired.`))return;const data=record()||{days:{},achievements:[],month:new Date().toISOString().slice(0,7)},today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);this.unlockIfGrown(data,levelFor(data));data.days={[today]:{meals:[],activity:'',bonusUsed:false,remark:''}};data.xp=0;data.pet=id;this.companion=companionFrom(id,PETS[id].label);data.companion=this.companion;localStorage.setItem(STORE,JSON.stringify(data));window.gentleFuelCompanion=this.companion;window.dispatchEvent(new CustomEvent('gentle-fuel-companion-change',{detail:data}));document.querySelectorAll('[data-pet3d]').forEach(host=>host.innerHTML='');this.mountViews();this.bind();this.render()}
  render(){const data=record()||{},xp=xpFor(data),level=levelFor(data),progress=level===4?'Companion journey complete':`${(xp%4).toFixed(1)} / 4.0 XP to Level ${level+1}`;if(this.unlockIfGrown(data,level))return this.render();document.querySelectorAll('[data-companion-name]').forEach(e=>e.textContent=this.companion.name);document.querySelectorAll('[data-pet-status]').forEach(e=>{e.textContent=level===4?`${this.companion.name} is now complete in your guidebook!`:`Every meal check-in helps ${this.companion.name} evolve.`;let line=e.parentElement.querySelector('[data-level-line]');if(!line){line=document.createElement('p');line.dataset.levelLine='';line.className='pet-level-line';e.insertAdjacentElement('afterend',line)}line.textContent=`Level ${level} / 4 · ${xp.toFixed(1)} XP · ${progress}`;});document.querySelectorAll('[data-xp-progress]').forEach(e=>e.textContent=progress);this.collection(data,level);this.bind()}
  showEncounter(){const modal=document.getElementById('starterEncounter');modal.hidden=false;let selected='bunny';const cards=[...modal.querySelectorAll('[data-starter]')];const select=id=>{selected=id;cards.forEach(c=>c.classList.toggle('is-picked',c.dataset.starter===id));modal.querySelector('[data-encounter-copy]').textContent=`${PETS[id].kind} wants to be your companion.`};cards.forEach(c=>c.onclick=()=>select(c.dataset.starter));select(selected);modal.querySelector('[data-adopt]').onclick=()=>{const name=modal.querySelector('input').value.trim()||PETS[selected].label;this.companion=companionFrom(selected,name);persist(this.companion);modal.hidden=true;window.dispatchEvent(new CustomEvent('gentle-fuel-companion-created',{detail:{pet:selected,name}}));this.mount()}}
}
function bootCompanion(){try{window.gentleFuelPet3D=new CompanionController()}catch(error){console.warn('Pet companion unavailable',error);document.querySelectorAll('[data-pet3d]').forEach(e=>e.innerHTML='<span class="pet-fallback">Your companion is waking up…</span>')}import('https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js').then(module=>{THREE=module;window.gentleFuelPet3D?.upgrade3D()}).catch(()=>console.info('Using built-in pet view while 3D library is unavailable'))}
window.addEventListener('DOMContentLoaded',bootCompanion);
